# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
locale: "en-US"

# Site Settings
title: Anurag Mishra
subtitle: AI Research Scientist
name: Anurag Mishra
description: AI Research Scientist | MS in AI at RIT | Machine Learning & NLP Researcher
url: https://i-anuragmishra.github.io
repository: i-anuragmishra/i-anuragmishra.github.io
logo: "/assets/images/profile.jpg"
search: true

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "/assets/images/profile.jpg"
  bio: "AI Research Scientist | MS in AI Student at RIT"
  location: "Rochester, NY"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:am2552@g.rit.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/i-anuragmishra"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/i-anuragmishra"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/i-anuragmishra"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/i-anuragmishra"

# Reading Files
include:
  - _pages
  - assets
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 