# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
locale: "en-US"

# Site Settings
title: "Anurag Mishra"
title_separator: "-"
subtitle: "AI Research Scientist"
name: "Anurag Mishra"
description: "AI Research Scientist | MS in AI at RIT | Machine Learning & NLP Researcher"
url: "https://i-anuragmishra.github.io"
baseurl: ""
repository: "i-anuragmishra/i-anuragmishra.github.io"

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "assets/images/profile.jpg"
  bio: "AI Research Scientist | MS in AI at RIT"
  location: "Rochester, NY"
  employer: 
  googlescholar: 
  email: "am4010@rit.edu"
  github: "i-anuragmishra"
  linkedin: "anurag-mishra-ai"

# Reading Files
include:
  - .htaccess
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true 