# Theme Settings
remote_theme: academicpages/academicpages.github.io
minimal_mistakes_skin: "default"
locale: "en-US"

# Site Settings
title: Anurag Mishra
subtitle: AI Research Scientist
name: Anurag Mishra
email: am2552@g.rit.edu
description: AI Research Scientist | MS in AI at RIT | Machine Learning & NLP Researcher
url: https://i-anuragmishra.github.io
baseurl: ""
repository: i-anuragmishra/i-anuragmishra.github.io
logo: "/assets/images/profile.jpg"
search: true

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: ""
    anonymize_ip: false

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "/assets/images/profile.jpg"
  bio: "AI Research Scientist | MS in AI Student at RIT"
  location: "Rochester, NY"
  employer: 
  pubmed:
  googlescholar: 
  email: "am2552@g.rit.edu"
  researchgate:
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "i-anuragmishra"
  google_plus:
  keybase:
  instagram:
  impactstory:
  lastfm:
  linkedin: "i-anuragmishra"
  orcid: 
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:
  wikipedia:

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-archives

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development 