# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"
locale: "en-US"

# Site Settings
title: "Anurag Mishra"
title_separator: "•"
subtitle: "AI Research"
name: "Anurag Mishra"
description: "AI Research • Machine Learning • NLP"
url: "https://i-anuragmishra.github.io"
baseurl: ""
repository: "i-anuragmishra/i-anuragmishra.github.io"

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "assets/images/profile.jpg"
  bio: "AI Research @ RIT"
  location: "Rochester, NY"
  email: "am4010@rit.edu"
  github: "i-anuragmishra"
  linkedin: "anurag-mishra-ai"

# Reading Files
include:
  - .htaccess
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  blog:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
  # _blog
  - scope:
      path: ""
      type: blog
    values:
      layout: single
      author_profile: true
      share: false 