# Site Settings
title: Anurag Mishra
email: am2552@g.rit.edu
description: >- 
  AI Research Scientist | MS in AI at RIT | Machine Learning & NLP Researcher
baseurl: ""
url: "https://i-anuragmishra.github.io"
github_username: i-anuragmishra
linkedin_username: i-anuragmishra
location: Rochester, NY

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Theme Settings
header_pages:
  - about.md
  - research.md
  - publications.md
  - experience.md
  - projects.md

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "/assets/images/profile.jpg"
  bio: "AI Research Scientist | MS in AI at RIT"
  location: "Rochester, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/i-anuragmishra"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/i-anuragmishra"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:am2552@g.rit.edu"

# Reading Files
include:
  - .htaccess
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test 