# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
locale: "en-US"

# Site Settings
title: "Anurag Mishra"
title_separator: "•"
subtitle: "AI Research"
name: "Anurag Mishra"
description: "AI Research • Machine Learning • NLP"
url: "https://i-anuragmishra.github.io"
baseurl: ""
repository: "i-anuragmishra/i-anuragmishra.github.io"

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "assets/images/profile.jpg"
  bio: "AI Research @ RIT"
  location: "Rochester, NY"
  email: "am4010@rit.edu"
  github: "i-anuragmishra"
  linkedin: "anurag-mishra-ai"

# Reading Files
include:
  - .htaccess
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true 